### ISSUE TITLE
`get_projects` should accept a namespace parameter

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub_db#12]
It would be nice to be able to pass a `namespace` parameter to the `get_projects` method of `PepAgent`. This way I don't have to manually filter out namespaces that are not relevant when pulling them down and it saves on network latency.

Something like this:

```python
projects = db.get_projects("geo")
```

**Comment by nleroy917** [comment]
Maybe this can be two things:

1. Just the project names, or
2. Full objects


**Option 1:**
```python
>>> projects = db.get_projects("geo")
>>> projects
>>> ['GSE123456', 'GSE987654', ... ]
```

**Option 2:**
```python 
>>> projects = db.get_projects("geo")
>>> projects
>>> [ 
    'GSE12345': {
          'samples': ...
    }
]
```

**Comment by Khoroshevskyi** [comment]
Added!
