### ISSUE TITLE
Add a `get_namespaces` method

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pephub_db#13]
This might not be **essential**, but could speed things up if implemented. It would be nice to have a function that obtains all the unique namespace's inside a pephub database. I envision the API being used as such:

```python
>>> nspaces = db.get_namespaces()
>>> nspaces
>>> ['demo', 'geo', 'nfcore' ... ]
```

This helps quickly populate a lot of the `html` splash pages we have.

**Comment by Khoroshevskyi** [comment]
Fixed!
