### ISSUE TITLE
retrieving projects

### ISSUE THREAD

**Issue by nsheff** [pepkit/pephub_db#3]
the readme says:

```python
pr_ob = projectDB.get_project(project_name='imply')
print(pr_ob.samples)
```
But I think you should not be able to retrieve a project by name, since it's not unique. instead, you should retrieve by *registry path*.

somthing like:

```python
pr_obj = projectDB.get_project("namespace/project")
```

you should use `ubiquerg.parse_registry_path` to parse this and then lookup.

**Comment by nleroy917** [comment]
Should be solved with latest updates.
